version: '3'

services: 
  web:
    build: .
    command: node index.js
    ports:
      - "3000:3000"
    container_name: web
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass
      MYSQL_HOST: db
  nginx: 
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  cerbot:
    image: cerbot/cerbot
    volumes: 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
# db:
#   image: orchardup/mysql
#   ports:
#     - "3306:3306"
#   environment:
#     MYSQL_DATABASE: myapp
#     MYSQL_USER: myapp
#     MYSQL_PASSWORD: mysecurepass
